# Generated by Django 4.2.6 on 2023-10-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
