# Generated by Django 4.2.6 on 2023-10-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0003_aimodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
